### PR TITLE
Moving to mock3 in python3

### PR DESCRIPTION
**Pull request by Rogalek**

### CODE REVIEW

**Review by jayvdb — APPROVED** [review]
Included in https://build.opensuse.org/request/show/832646

**Comment by mgorny** [comment]
Python 3 has `unittest.mock`, so no external package is required.

**Comment by Rogalek** [comment]
so what now? is it merged or what?

**Comment by c-oreills** [comment]
Apologies for the delay - this is now merged! Thank you for your contribution.

**Pull request merged**
